# Generated by Django 3.2.7 on 2021-11-16 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211112_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 6, 56, 26, 8761, tzinfo=utc)),
        ),
    ]
